### ISSUE TITLE
Remove requirement for custom bundler config

### ISSUE THREAD

**Issue by bergos** [rubensworks/jsonld-streaming-parser.js#105]
I'm trying to remove the requirement for custom bundler configs for all `@rdfjs` packages. I stumbled over [this line](https://github.com/creationix/jsonparse/blob/master/jsonparse.js#LL1) in the `jsonparse` package. It works after manually adding the following line on top of `jsonparse.js`:

```javascript
var { Buffer } = require('buffer')
```

I'm aware there is a bounty for #76, and I also saw #100. That's why I'm asking how to solve this problem. `jsonparse` didn't receive any updates for six years. A quick and pragmatic solution would be to fork `jsonparse`, fix only the `Buffer` import, and use the forked package. That would also be my proposal if there aren't any other plans which would also solve this problem.

@rubensworks How can I help if you agree with the proposed solution? I can create and publish the fork, but if you have some more changes in mind, keeping the fork under your user would be better.

**Comment by rubensworks** [comment]
We have a WIP fork of jsonparse.js in https://github.com/comunica/json-event-parser.js, but it does much more than including the buffer dependency.
It is unknown at this stage when the migration to json-event-parser.js will be finished, so perhaps we can have an interim solution for now indeed.

So yes, I agree with the proposed solution! (It will likely be temporary though)
