### ISSUE TITLE
[Bug]: Prefix not expanded

### ISSUE THREAD

**Issue by jeswr** [rubensworks/jsonld-streaming-parser.js#112]
Reproduction.

Code:
```ts
import { JsonLdParser } from 'jsonld-streaming-parser';
import streamifyString from 'streamify-string';

const stream = streamifyString(`{
  "@context":[
    {"ex":"https://example.org/ns/"},
    "https://www.w3.org/2018/credentials/v1"
  ],
  "@id": "ex:someCredentialInstance",
  "@type": "VerifiableCredential"
}`)

const parser = new JsonLdParser();
stream
.pipe(parser)
.on('data', console.log)
.on('error', console.error)
.on('end', () => console.log('All triples were parsed!'));
```

Output:
```
Quad {
  termType: 'Quad',
  value: '',
  subject: NamedNode {
    termType: 'NamedNode',
    value: 'ex:someCredentialInstance'
  },
  predicate: NamedNode {
    termType: 'NamedNode',
    value: 'http://www.w3.org/1999/02/22-rdf-syntax-ns#type'
  },
  object: NamedNode {
    termType: 'NamedNode',
    value: 'https://www.w3.org/2018/credentials#VerifiableCredential'
  },
  graph: DefaultGraph { termType: 'DefaultGraph', value: '' }
}
```

Expected Output:
The subject value should be https://example.org/ns/someCredentialInstance, which is what we get when testing the same input on https://json-ld.org/playground/.

Note that this behaves as expected on inputs like
```json
{
  "@context":[
    {"ex":"https://example.org/ns/"}
  ],
  "@id": "ex:someCredentialInstance",
  "@type": "ex:VerifiableCredential"
}
```

**Comment by rubensworks** [comment]
That's interesting. Suprised such a bug for this simple document even exists.

The fact that it works as expected without the remote context indicates that it might be an issue in https://github.com/rubensworks/jsonld-context-parser.js.

**Comment by jeswr** [comment]
> The fact that it works as expected without the remote context indicates that it might be an issue in https://github.com/rubensworks/jsonld-context-parser.js.

Indeed - I've further narrowed it down to seemingly be a bug with the way the `@protected` keyword behaves. In particular the following has the same bug as above, but it is resolved if the `"@protected": true,` statement is removed.

```json
{
  "@context": [
    { "ex": "https://example.org/ns/" },
    {
      "@version": 1.1,
      "@protected": true,
      "VerifiableCredential": {
        "@id": "https://www.w3.org/2018/credentials#VerifiableCredential"
      }
    }
  ],
  "@id": "ex:someCredentialInstance",
  "@type": "VerifiableCredential"
}
```

**Comment by rubensworks** [comment]
Yeah, the handling of `@protected` is definitely not trivial. I've broken my head over this many times before already 😅

**Comment by jeswr** [comment]
@rubensworks I've started on a fix for this over in https://github.com/rubensworks/jsonld-context-parser.js/pull/61, but it is hacky.

The problem seems to be that when the contexts are merged (https://github.com/rubensworks/jsonld-context-parser.js/blob/2f6983783266e7a73eab69acb2378f0bac9720e9/lib/ContextParser.ts#L771-L777) top level `@version`, `@protected` (and any other keyword allowed at the top-level) has the potential to be inserted/overridden to contexts which do not have, or have conflicting values for those keywords.

The fix above trys to resolve this for the `@protected` case by calling functions to push the `@protected` keyword down out of the outer context, but this breaks tests around prefixes for reasons that are unknown to me, and doesn't fix the problem in general for other keywords.

Do you want to proceed with the current approach of trying to call `applyScopedProtected` on the context and see if I can fix the [one broken test for prefixes](https://github.com/rubensworks/jsonld-context-parser.js/actions/runs/6234850425/job/16922855935?pr=61)? Is there another cleaner approach you can think of that solves the keyword overriding problem in general?
