### ISSUE TITLE
[Bug]: Type specific contexts not used when `@type` is aliased.

### ISSUE THREAD

**Issue by jeswr** [rubensworks/jsonld-streaming-parser.js#115]
In particular, if I have the context:
```json
{
  "type": "@type",
  "VerifiableCredential": {
    "@id": "https://www.w3.org/2018/credentials#VerifiableCredential",
    "@context": {
      "credentialSubject": {"@id": "https://www.w3.org/2018/credentials#credentialSubject", "@type": "@id"},
    }
  },
}
```

Then the following correctly gets parsed

```json
{
  "@context": /* above context */,
  "@id": "https://some.credential",
  "credentialSubject": { "@id": "https://some.requestor" },
  "@type": [ "VerifiableCredential" ]
 }
```

however when we parse the following it is missing the triple `<https://some.credential> <https://www.w3.org/2018/credentials#credentialSubject> <https://some.requestor> .`

```json
{
  "@context": /* above context */,
  "@id": "https://some.credential",
  "credentialSubject": { "@id": "https://some.requestor" },
  "type": [ "VerifiableCredential" ]
 }
```

I am actively investigating a fix.

**Comment by rubensworks** [comment]
This is the relevant function that _should_ be called, but perhaps is not: https://github.com/rubensworks/jsonld-streaming-parser.js/blob/master/lib/Util.ts#L715

I do remember having some tests on aliasing `@type`, so perhaps it's related to something else.

Maybe the array value of `type` has something to do with it?

**Comment by jeswr** [comment]
I tried using a key of `ty` rather than `type`. I also tried having a value of `"VerifiableCredential"` rather than `[ "VerifiableCredential" ]`.

In both cases the error persists.

**Comment by jeswr** [comment]
As far as I can tell the problem is that the function you point to is not being used in https://github.com/rubensworks/jsonld-streaming-parser.js/blob/10c21b24e51d388fce6d465ba27ef50fbdf06ec3/lib/JsonLdParser.ts#L456-L457.

I'm currently working to try and resolve this, but am somewhat unsure what the arguments that I need to call it with are.

**Comment by rubensworks** [comment]
Right, that will be a bit tricky.
It could be that additional contexts will still be added _after_ the type job is added.
So we may need an additional step where some of the `contextAwaitingJobs` are moved to `typeJobs` once all contexts are available.
