### ISSUE TITLE
Support application/activity+json

### ISSUE THREAD

**Issue by pietercolpaert** [rubensworks/jsonld-streaming-parser.js#124]
ActivityStreams publish perfectly valid JSON-LD, but constrain themselves to a specific JSON frame. Therefore, they don’t use the content-type application/ld+json, but use the more specific application/activity+json. While they should probably have used the profile headers, they didn’t and by doing that they broke support for standard JSON-LD libraries.

As there is quite some application/activity+json around, I’d like to ask permission to pull request this in this library

**Comment by rubensworks** [comment]
Sure, I'm definitely open to that!

We probably need a change here: https://github.com/rubensworks/jsonld-streaming-parser.js/blob/master/lib/JsonLdParser.ts#L110-L136
Maybe we even want to keep a list of well-known JSON-LD content types, which defaults to `[ 'application/activity+json' ]`

For comunica and rdf-parse, we'll also need a change here: https://github.com/comunica/comunica/blob/master/packages/actor-rdf-parse-jsonld/lib/ActorRdfParseJsonLd.ts#L21-L29

**Comment by pietercolpaert** [comment]
Pull request ready for review - also happy to then PR this into rdf-parse
