### ISSUE TITLE
Empty @id outputs no triples, correct?

### ISSUE THREAD

**Issue by mielvds** [rubensworks/jsonld-streaming-parser.js#20]
According to the spec, an empty `@id` resolves to the document base: https://www.w3.org/TR/json-ld/#advanced-concepts.

The JSON snippet `[{"@id":"","http://schema.org/name":"Foo"}]` should take some sort of uri as subject when parsed. When parsing this from a local file, the streaming parser does not produce any triples. I wonder whether it should mint a "file://" URI instead? Agreed, this is gray area stuff, hard to spot what the spec says.

**Comment by rubensworks** [comment]
I'm pretty sure that correct behaviour is to ignore relative IRIs without a baseIRI. In any case, no IRIs should be minted, but it's possible that the spec allows relative IRIs within RDF terms, I'll have to check.

But it's already possible to mint `file://` IRIs by setting the `baseIRI` option in the configuration as follows: https://github.com/rubensworks/jsonld-streaming-parser.js#configuration

**Comment by rubensworks** [comment]
For reference, the Ruby JSON-LD implementation is consistent with this behaviour: http://rdf.greggkellogg.net/distiller

**Comment by mielvds** [comment]
👌 Already using the baseIRI now, but was wondering. Follow-up question: should you get a warning by the parser? I lost some time before I figured it out :p

**Comment by rubensworks** [comment]
> should you get a warning by the parser?

This is actually behaviour that is defined by the spec.

Honestly, I was also annoyed by this fact, which is why I added the `errorOnInvalidIris` option. Useful for development, but should probably not be used in production.
