### ISSUE TITLE
Parsing fails on aliasing keyword "@graph"

### ISSUE THREAD

**Issue by ssstolk** [rubensworks/jsonld-streaming-parser.js#47]
According to the JSON-LD spec (both 1.0 and 1.1):
> Each of the JSON-LD keywords, except for @context, may be aliased to application-specific keywords.

[This JSON playground](https://json-ld.org/playground/#startTab=tab-nquads&json-ld=%7B%22%40context%22%3A%5B%22http%3A%2F%2Fwww.w3.org%2Fns%2Fanno.jsonld%22%2C%7B%22content%22%3A%7B%22%40id%22%3A%22%40graph%22%2C%22%40container%22%3A%22%40index%22%7D%7D%5D%2C%22content%22%3A%7B%22Annotation%22%3A%5B%7B%22type%22%3A%22Annotation%22%2C%22id%22%3A%22https%3A%2F%2Fw3id.org%2Fevoke%2Fid%2Fannotation%2F9596ec9e-e22a-4162-9a16-78bfc5aca1f0%22%2C%22created%22%3A%222019-12-24T14%3A22%3A23.458Z%22%2C%22motivation%22%3A%22tagging%22%7D%5D%7D%7D) shows this in action for aliasing the keyword "@graph".

With this example as input, however, the parser fails with the following error.
> Illegal keyword alias in term value, found: 'content': '{"@id":"@graph","@container":"@index"}'

**Comment by rubensworks** [comment]
Thanks for reporting, I'll look into it as soon as possible!

**Comment by rubensworks** [comment]
Will be fixed in release 2.0.0 of this library.
