### ISSUE TITLE
Detect context from content of JSON media type responses in fromHttpResponse

### ISSUE THREAD

**Issue by alexkreidler** [rubensworks/jsonld-streaming-parser.js#69]
I am trying to use an API service that returns fully compliant (streaming-compliant as well) JSON-LD. However, for whatever reason, they publish it with a `Content-Type` of `application/json`, and don't include any Link headers. The API is the [US Census API](https://api.census.gov/data.json).

The context is a remote context referenced via the `@context` key in the JSON-LD.

Right now I'm getting `Missing context link header for media type application/json on https://api.census.gov/data.json`.

It would be great to add an option, or potentially change the default, so that if the parser fails to find a Link header for the JSON, it attempts to interpret it as JSON-LD and load the context that way.

Let me know how this sounds. Thanks!

By the way, I'm using `rdf-dereference` as the calling tool.

**Comment by rubensworks** [comment]
> they publish it with a Content-Type of application/json, and don't include any Link headers.

Strictly speaking, this is not valid JSON-LD according to the spec, and the way this library (and all other existing JSON-LD 1.1 libraries) handles this is spec-compliant. So accepting this document would in fact be incorrect.

The best way forward would be to contact the publishers of the API, and ask them to use the proper content type. This would not only fix the problem with this library, but also all other libraries that parse JSON-LD 1.1.

> streaming-compliant as well

There's no `http://www.w3.org/ns/json-ld#streaming` profile present, which is required to enable streaming mode: https://www.w3.org/TR/json-ld11-streaming/#streaming-profile

---

That being said, I'm definitely open to a PR that somehow adds an option to ignore the content type of the response, and always assume JSON-LD.
