### ISSUE TITLE
Blank nodes incorrectly linked

### ISSUE THREAD

**Issue by rubensworks** [rubensworks/jsonld-streaming-parser.js#72]
```json
{
   "@context":"https://schema.org/",
   "@type":"Dataset",
   "@id":"http://data.bibliotheken.nl/id/dataset/rise-alba",
   "name":"Alba amicorum van de Koninklijke Bibliotheek",
   "description":"Alba amicorum van de Koninklijke Bibliotheek, een dataset gedefinieerd voor het Europeana Rise of Literacy project.",
   "url":"https://www.kb.nl/bronnen-zoekwijzers/kb-collecties/moderne-handschriften-vanaf-ca-1550/alba-amicorum",
   "identifier":"http://data.bibliotheken.nl/id/dataset/rise-alba",
   "keywords":[
      "alba amicorum"
   ],
   "license":"http://creativecommons.org/publicdomain/zero/1.0/",
   "creator":{
      "@type":"Organization",
      "url":"https://www.kb.nl/",
      "name":"Koninklijke Bibliotheek",
      "sameAs":"https://ror.org/02w4jbg70"
   },
   "distribution":[
      {
         "@type":"DataDownload",
         "encodingFormat":"application/rdf+xml",
         "contentUrl":"http://data.bibliotheken.nl/id/dataset/rise-alba.rdf"
      },
      {
         "@type":"DataDownload",
         "encodingFormat":"text/turtle",
         "contentUrl":"http://data.bibliotheken.nl/id/dataset/rise-alba.ttl"
      },
      {
         "@type":"DataDownload",
         "encodingFormat":"application/n-triples",
         "contentUrl":"http://data.bibliotheken.nl/id/dataset/rise-alba.nt"
      },
      {
         "@type":"DataDownload",
         "encodingFormat":"application/ld+json",
         "contentUrl":"http://data.bibliotheken.nl/id/dataset/rise-alba.json"
      }
   ]
}
```

**Comment by ddeboer** [comment]
Hey @rubensworks, would it be hard to fix this issue? We’re somewhat blocked now in our use of CONSTRUCT and SELECT queries. Of course, we could just dereference the whole thing and `match()` over it, but that feels rather inelegant and inefficient.

I can see that the`BlankNodeScoped.skolemized` values are perfectly fine, it’s just the blank node generation that borks.

**Comment by rubensworks** [comment]
> would it be hard to fix this issue

Not sure yet. I suspect there's a problem with scope location of the values in the array.
If so, something is probably going wrong in our [`EntryHandlerArrayValue`](https://github.com/rubensworks/jsonld-streaming-parser.js/blob/master/lib/entryhandler/EntryHandlerArrayValue.ts).
(I'm out of bandwidth myself atm, so no idea if or when I may be able to look into this)

In any case, a workaround until this issue is fixed may be to add identifiers to each download, e.g.:
```json
   "distribution":[
      {
         "@id": "#download1",
         "@type":"DataDownload",
         "encodingFormat":"application/rdf+xml",
         "contentUrl":"http://data.bibliotheken.nl/id/dataset/rise-alba.rdf"
      },
  ]
```
But this is of course only possible if you can influence how this data is generated.

**Comment by rubensworks** [comment]
This seems to have been no issue in this lib after all (but https://github.com/comunica/comunica/issues/773).
