### ISSUE TITLE
No error on incomplete JSON

### ISSUE THREAD

**Issue by bergos** [rubensworks/jsonld-streaming-parser.js#83]
The parser doesn't emit an error when the JSON stream is incomplete. The used `jsonparser` package has a property `mode` that could be used to detect that case. The property is used to keep track of the current context like object and array. After the last `}` or `]` was written, the `mode` is changed to `undefined`. At the end of the incoming stream, the `mode` property could be checked and an error emitted if the `mode` is not `undefined`. Below is an example to reproduce the problem:

```javascript
const { promisify } = require('util')
const rdf = require('@rdfjs/data-model')
const { JsonLdParser } = require('jsonld-streaming-parser')
const { finished, Readable } = require('readable-stream')

async function main () {
  const input = new Readable({
    read: () => {
      input.push('{')
      input.push(null)
    }
  })

  const parser = new JsonLdParser({
    dataFactory: rdf,
    streamingProfile: false
  })

  input.pipe(parser)
  parser.resume()

  await promisify(finished)(parser)

  console.log(parser.jsonParser.mode)
}

main()
```

**Comment by rubensworks** [comment]
> The used jsonparser package has a property mode that could be used to detect that case.

Aha, I wasn't aware of that option.
